# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.ssh.insert_key = false
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "256"]
    end

    # APPLICATION SERVER 1
    config.vm.define "app1" do |app|
        app.vm.hostname = "orc-app1.dev"
        app.vm.box = "geerlingguy/centos7"
        app.vm.network :private_network, ip: "192.168.60.4"
    end 

    # APPLICATION SERVER 2
    config.vm.define "app2" do |app|
        app.vm.hostname = "orc-app2.dev"
        app.vm.box = "geerlingguy/centos7"
        app.vm.network :private_network, ip: "192.168.60.5"
    end 
    
    # Database 
    config.vm.define "db" do |app|
        app.vm.hostname = "orc-db.dev"
        app.vm.box = "geerlingguy/centos7"
        app.vm.network :private_network, ip: "192.168.60.6"
    end 
end
